{% set version = "1.3.11" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-geepack
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/geepack_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/geepack/geepack_{{ version }}.tar.gz
  sha256: 29e2f0d314e75de748f33438b5b1282f469d163e29534c61616c257b2955e478

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [unix]
    - {{ stdlib("c") }}          # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-broom
    - r-magrittr
  run:
    - r-base
    - r-mass
    - r-broom
    - r-magrittr

test:
  commands:
    - $R -e "library('geepack')"           # [not win]
    - "\"%R%\" -e \"library('geepack')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=geepack
  license: GPL-3.0-or-later
  summary: Generalized estimating equations solver for parameters in mean, scale, and correlation structures, through mean link, scale link, and correlation link. Can also handle clustered categorical responses.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
