{% set version = "1.3.12" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-geepack
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/geepack_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/geepack/geepack_{{ version }}.tar.gz
  sha256: e01be9555155ecd6d4dee2e566066c2a6e0953d0e3a58bb31fa5c07f3834054d

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
  skip: true  # [ppc64le]

requirements:
  build:
    - {{ compiler('c') }}        # [unix]
    - {{ stdlib("c") }}          # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-mass                       # [build_platform != target_platform]
    - r-broom                      # [build_platform != target_platform]
    - r-magrittr                   # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-broom
    - r-magrittr
  run:
    - r-base
    - r-mass
    - r-broom
    - r-magrittr

test:
  commands:
    - $R -e "library('geepack')"           # [not win]
    - "\"%R%\" -e \"library('geepack')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=geepack
  license: GPL-3.0-or-later
  summary: Generalized estimating equations solver for parameters in mean, scale, and correlation structures, through mean link, scale link, and correlation link. Can also handle clustered categorical responses.
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
