{% set version = "1.3.9" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-geepack
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://cran.r-project.org/src/contrib/geepack_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/geepack/geepack_{{ version }}.tar.gz
  sha256: a106fdf99a7070243c412f0117f0f4e3954b2bae81266fba272e9c85040dcde7

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-mass
    - r-broom
    - r-magrittr
  run:
    - r-base
    - r-mass
    - r-broom
    - r-magrittr

test:
  commands:
    - $R -e "library('geepack')"  # [not win]
    - "\"%R%\" -e \"library('geepack')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=geepack
  license: GPL-3.0-or-later
  summary: Generalized estimating equations solver for parameters in mean, scale, and correlation structures, through mean link, scale link, and correlation link. Can also handle clustered categorical responses.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
